trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    echo "Hello"
    echo "##vso[task.setvariable variable=psJobVariable;isOutput=true]some_value"

- script: |
    echo "$(psJobVariable)"

- powershell: |
    # Generate the GitHub host URL
    $GITHUB_HOST="https://"+"$(Build.Repository.Uri)".split("/")[2]
    $env:TEST="hello"
    Write-Output '##vso[task.setvariable variable=GitHubHost;isOutput=true]$GITHUB_HOST'
    
    # Generate Repo name in Org/Repo format and assign it to GitHubRepo
    $GITHUB_ORG="$(Build.Repository.Uri)".split("/")[3]
    $GITHUB_REPO_NAME="$(Build.Repository.Uri)".split("/")[4] -replace ".git",""
    $GITHUB_REPO=$GITHUB_ORG+ "/" +$GITHUB_REPO_NAME
    Write-Output '##vso[task.setvariable variable=GitHubRepo;isOutput=true]$GITHUB_REPO'
    
    # DEBUG
    Write-Output "GITHUB_REPO = $GITHUB_REPO"
    Write-Output "GITHUB_HOST = $GitHubHost"
  name: setVarsStep  
  displayName: 'Initialise the necessary variables for Code Scanning'

- powershell: |
    Write-Output "GITHUB VAR: $(setVarsStep.GitHubRepo)"
    Write-Output "Test is $env:TEST"
  name: checkVars
  displayName: 'temp'
